// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gy7Lt_rSXNZ0LXDa6qj9f0smcq_8OJw',
    appId: '1:598816233731:web:9fefacc1bd9c2832b67136',
    messagingSenderId: '598816233731',
    projectId: 'covid19-6194b',
    authDomain: 'covid19-6194b.firebaseapp.com',
    storageBucket: 'covid19-6194b.appspot.com',
    measurementId: 'G-NXEBJWS60K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyyrkQQVe47o5LdTHK8XIUbDV2NMLsXJg',
    appId: '1:598816233731:android:91111696720d0e5cb67136',
    messagingSenderId: '598816233731',
    projectId: 'covid19-6194b',
    storageBucket: 'covid19-6194b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8RrhqW898Aae84HnvLLExBAARqJPRvU',
    appId: '1:598816233731:ios:e2f75766a4a12079b67136',
    messagingSenderId: '598816233731',
    projectId: 'covid19-6194b',
    storageBucket: 'covid19-6194b.appspot.com',
    iosClientId: '598816233731-aa9jsj9biqd0t9e1cd4l7bdk58os0po8.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalExam',
  );
}
